/**
 * Tests for Mesh Exporter utilities
 */
import { describe, it, expect } from 'vitest'

describe('Mesh Exporter', () => {
    describe('OBJ Export Format', () => {
        it('should generate valid OBJ header', () => {
            const header = `# OBJ file generated by Sharp
# Vertices with colors (v x y z r g b)
`
            expect(header).toContain('OBJ')
            expect(header).toContain('Vertices')
        })

        it('should format vertex line correctly', () => {
            const x = 1.5, y = 2.0, z = 3.5
            const r = 0.8, g = 0.5, b = 0.2

            const line = `v ${x} ${y} ${z} ${r} ${g} ${b}`

            expect(line).toMatch(/^v [\d.-]+ [\d.-]+ [\d.-]+ [\d.-]+ [\d.-]+ [\d.-]+$/)
        })
    })

    describe('PLY Export Format', () => {
        it('should generate valid PLY header', () => {
            const vertexCount = 1000
            const header = `ply
format ascii 1.0
element vertex ${vertexCount}
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
`
            expect(header).toMatch(/^ply/)
            expect(header).toContain(`element vertex ${vertexCount}`)
            expect(header).toContain('end_header')
        })

        it('should convert float colors to uchar', () => {
            const floatColors = [0.0, 0.5, 1.0, 0.25, 0.75]

            floatColors.forEach(f => {
                const uchar = Math.round(Math.max(0, Math.min(1, f)) * 255)
                expect(uchar).toBeGreaterThanOrEqual(0)
                expect(uchar).toBeLessThanOrEqual(255)
            })
        })

        it('should clamp out-of-range colors', () => {
            const badColors = [-0.5, 1.5, 2.0, -1.0]

            badColors.forEach(f => {
                const clamped = Math.max(0, Math.min(1, f))
                expect(clamped).toBeGreaterThanOrEqual(0)
                expect(clamped).toBeLessThanOrEqual(1)
            })
        })
    })

    describe('GLB Export', () => {
        it('should set correct MIME type', () => {
            const mimeType = 'model/gltf-binary'
            expect(mimeType).toBe('model/gltf-binary')
        })

        it('should use .glb extension', () => {
            const filename = 'model.glb'
            expect(filename.endsWith('.glb')).toBe(true)
        })
    })

    describe('File Naming', () => {
        it('should generate valid filenames', () => {
            const jobId = 'abc-123-def'
            const formats = ['obj', 'ply', 'glb'] as const

            formats.forEach(format => {
                const filename = `splat_${jobId}.${format}`
                expect(filename).toMatch(/^splat_[\w-]+\.\w+$/)
            })
        })

        it('should sanitize job IDs in filenames', () => {
            const dangerousId = '../../../etc/passwd'
            const safeId = dangerousId.replace(/[^a-zA-Z0-9-_]/g, '_')

            expect(safeId).not.toContain('/')
            expect(safeId).not.toContain('..')
        })
    })

    describe('Geometry Validation', () => {
        it('should require geometry for export', () => {
            const geometry = null
            expect(geometry).toBeNull()
            // Export should fail gracefully when geometry is null
        })

        it('should have position attribute', () => {
            // Mock geometry structure
            const mockGeometry = {
                attributes: {
                    position: { count: 100, array: new Float32Array(300) },
                    color: { count: 100, array: new Float32Array(300) },
                }
            }

            expect(mockGeometry.attributes.position).toBeDefined()
            expect(mockGeometry.attributes.position.count).toBe(100)
        })

        it('should have matching position and color counts', () => {
            const positionCount = 100
            const colorCount = 100

            expect(positionCount).toBe(colorCount)
        })
    })

    describe('Download Blob Creation', () => {
        it('should create blob with correct type for OBJ', () => {
            const content = 'v 0 0 0'
            const blob = new Blob([content], { type: 'text/plain' })

            expect(blob.size).toBeGreaterThan(0)
            expect(blob.type).toBe('text/plain')
        })

        it('should create blob with correct type for PLY', () => {
            const content = 'ply\nformat ascii 1.0'
            const blob = new Blob([content], { type: 'application/octet-stream' })

            expect(blob.size).toBeGreaterThan(0)
        })
    })
})

describe('Export Error Handling', () => {
    it('should handle missing color attribute gracefully', () => {
        const hasColors = false
        const defaultColor = [0.5, 0.5, 0.5]

        if (!hasColors) {
            expect(defaultColor).toHaveLength(3)
            expect(defaultColor.every(c => c >= 0 && c <= 1)).toBe(true)
        }
    })

    it('should handle empty geometry', () => {
        const vertexCount = 0
        expect(vertexCount).toBe(0)
        // Should return early or throw specific error
    })
})
